name: Get Repository Lannguages
description: Gets repository languages using the GitHub API
author: Iker Saint

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: activity
  color: blue

# Define your inputs here.
inputs:
  gh-token:
    description: GH token used to retrieve the repository languages
    required: false
    default: ${{ github.token }}
  repository:
    description: The owner and repository name (owner/repository)
    required: false
    default: ${{ github.repository }}
  allowed-languages:
    description: >
      Allowed languages list separated by commas; those not in this list are
      filtered out. e.g: "Javascript,Typescript,Java,C#,Golang,Rust,Python"
    required: false
    default: ''
  allowed-threshold:
    description: >
      Minimum language percentage for it to be included in the results
    required: false
    default: '0'

# Define your outputs here.
outputs:
  languages:
    description: Repository languages as a string contaning a JSON array

runs:
  using: node16
  main: dist/index.js
